//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusuoStoreIg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comuna
    {
        public string nomC { get; set; }
        public int idR { get; set; }
    
        public virtual region region { get; set; }
    }
}
