//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusuoStoreIg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KusuoStoreEn : DbContext
    {
        public KusuoStoreEn()
            : base("name=KusuoStoreEn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carcasa> carcasa { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<comuna> comuna { get; set; }
        public virtual DbSet<persona> persona { get; set; }
    }
}
