//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusuoStoreIg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int IDpedido { get; set; }
        public int IDus { get; set; }
        public int IDcar { get; set; }
        public int cantidad { get; set; }
        public double preciot { get; set; }
    
        public virtual carcasa carcasa { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
