//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusuoStoreIg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.pedido = new HashSet<pedido>();
            this.persona = new HashSet<persona>();
        }
    
        public int IDus { get; set; }
        [Required(ErrorMessage = "Se requiere este campo lleno")]
        [Display(Name = "Nombre de usuario")]
        public string nomusuario { get; set; }
        [Required(ErrorMessage = "Se requiere este campo lleno")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string contraseña { get; set; }
        [Required(ErrorMessage = "Se requiere este campo lleno")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar contraseña")]
        public string recontraseña { get; set; }
        public string tipousuario { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Se requiere este campo lleno")]       
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona> persona { get; set; }
    }
}
